{% set name = "twilio" %}
{% set version = "7.16.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9ffc1d96331aedaba8fd0b7be691125057ace3e425a3c8d11b75039d788e735

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - PyJWT >=2.0.0,<3.0.0
    - python >=3.6
    - pytz
    - requests >=2.0.0

test:
  requires:
    - pip
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.twiml
  commands:
    - pip check

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
