{% set name = "twilio" %}
{% set version = "9.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb80b31d4d9e55c33872efef7fb99373149ed4093f21c56cf582797da45862f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - PyJWT >=2.0.0,<3.0.0
    - python >={{ python_min }}
    - pytz
    - requests >=2.0.0
    - aiohttp >=3.8.4
    - aiohttp-retry >=2.8.3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.twiml
  commands:
    - pip check

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
