{% set name = "twilio" %}
{% set version = "9.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd754371353855438a8cf0c38f54580d474afe9655af2d81edb6dbabd8d785c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - PyJWT >=2.0.0,<3.0.0
    - python >=3.7
    - pytz
    - requests >=2.0.0
    - aiohttp >=3.8.4
    - aiohttp-retry >=2.8.3

test:
  requires:
    - pip
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.twiml
  commands:
    - pip check

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
