{% set name = "twilio" %}
{% set version = "6.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 284040aa4cd504d67e95cde17db38d4d11454ac8bd43cab94f66694241b962af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pyjwt >=1.4.2
    - python
    - pytz
    - requests >=2.0.0
    - six

test:
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.rest.api
    - twilio.rest.authy
    - twilio.rest.autopilot
    - twilio.rest.chat
    - twilio.rest.fax
    - twilio.rest.insights
    - twilio.rest.lookups
    - twilio.rest.messaging
    - twilio.rest.monitor
    - twilio.rest.notify
    - twilio.rest.preview
    - twilio.rest.pricing
    - twilio.rest.proxy
    - twilio.rest.serverless
    - twilio.rest.studio
    - twilio.rest.sync
    - twilio.rest.taskrouter
    - twilio.rest.trunking
    - twilio.rest.verify
    - twilio.rest.video
    - twilio.rest.voice
    - twilio.rest.wireless
    - twilio.twiml

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
